name: Tests

on:
  pull_request:
    branches: [main]
  
jobs:
  build:
    runs-on: macos-12
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '14'
    - run: yarn install --frozen-lockfile
    - run: yarn tsc
    - run: yarn lint
    - run: yarn test
    - run: yarn e2e:ios:build-release
    - run: yarn e2e:ios-release
